const students = [{
    "id": 1,
    "first_name": "Temp",
    "last_name": "Sywell",
    "email": "tsywell0@buzzfeed.com",
    "gender": "Male",
    "ip_address": "156.226.88.130"
  }, {
    "id": 2,
    "first_name": "Hal",
    "last_name": "Jumeau",
    "email": "hjumeau1@dell.com",
    "gender": "Male",
    "ip_address": "110.243.126.219"
  }, {
    "id": 3,
    "first_name": "Gail",
    "last_name": "McElvogue",
    "email": "gmcelvogue2@abc.net.au",
    "gender": "Female",
    "ip_address": "217.181.185.58"
  }, {
    "id": 4,
    "first_name": "Rick",
    "last_name": "Loughman",
    "email": "rloughman3@nbcnews.com",
    "gender": "Male",
    "ip_address": "151.179.159.163"
  }, {
    "id": 5,
    "first_name": "Lodovico",
    "last_name": "Chesshyre",
    "email": "lchesshyre4@psu.edu",
    "gender": "Genderfluid",
    "ip_address": "136.186.178.155"
  }, {
    "id": 6,
    "first_name": "Georgena",
    "last_name": "Bunworth",
    "email": "gbunworth5@surveymonkey.com",
    "gender": "Female",
    "ip_address": "143.79.130.93"
  }, {
    "id": 7,
    "first_name": "Marty",
    "last_name": "Stephen",
    "email": "mstephen6@google.com.br",
    "gender": "Male",
    "ip_address": "220.113.156.7"
  }, {
    "id": 8,
    "first_name": "Grissel",
    "last_name": "Dargue",
    "email": "gdargue7@woothemes.com",
    "gender": "Female",
    "ip_address": "87.13.149.181"
  }, {
    "id": 9,
    "first_name": "Avictor",
    "last_name": "O'Fallon",
    "email": "aofallon8@netscape.com",
    "gender": "Male",
    "ip_address": "66.180.196.200"
  }, {
    "id": 10,
    "first_name": "Garik",
    "last_name": "Dmytryk",
    "email": "gdmytryk9@cocolog-nifty.com",
    "gender": "Male",
    "ip_address": "5.15.129.177"
  }]

module.exports = students; 